-- BUSINESS ANALYSIS


-- Total revenue
SELECT
    SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM SALES_TRANSACTIONS;


-- Total units sold
SELECT
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD
FROM SALES_TRANSACTIONS;


-- Average order value
SELECT
    ROUND(
        SUM(QUANTITY * UNIT_PRICE) / COUNT(*),
        2
    ) AS AVERAGE_ORDER_VALUE
FROM SALES_TRANSACTIONS;


-- Top 5 products by revenue
SELECT
    PRODUCT_NAME,
    SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM SALES_TRANSACTIONS
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;


-- Top 5 cities by revenue
SELECT
    CITY,
    SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM SALES_TRANSACTIONS
GROUP BY CITY
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;


-- Best payment mode by revenue
SELECT
    PAYMENT_MODE,
    SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM SALES_TRANSACTIONS
GROUP BY PAYMENT_MODE
ORDER BY TOTAL_REVENUE DESC;


-- Best payment mode by number of transactions
SELECT
    PAYMENT_MODE,
    COUNT(*) AS TOTAL_TRANSACTIONS
FROM SALES_TRANSACTIONS
GROUP BY PAYMENT_MODE
ORDER BY TOTAL_TRANSACTIONS DESC;


-- Best-selling product by quantity
SELECT
    PRODUCT_NAME,
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM SALES_TRANSACTIONS
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_QUANTITY DESC
LIMIT 1;


-- Lowest-selling product by quantity
SELECT
    PRODUCT_NAME,
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM SALES_TRANSACTIONS
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_QUANTITY ASC
LIMIT 1;


-- Monthly revenue
SELECT
    YEAR(TRANSACTION_DATE) AS TRANSACTION_YEAR,
    MONTH(TRANSACTION_DATE) AS MONTH_NUMBER,
    MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME,
    SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM SALES_TRANSACTIONS
GROUP BY
    YEAR(TRANSACTION_DATE),
    MONTH(TRANSACTION_DATE),
    MONTHNAME(TRANSACTION_DATE)
ORDER BY
    TRANSACTION_YEAR,
    MONTH_NUMBER;


-- Yearly revenue
SELECT
    YEAR(TRANSACTION_DATE) AS TRANSACTION_YEAR,
    SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM SALES_TRANSACTIONS
GROUP BY YEAR(TRANSACTION_DATE)
ORDER BY TRANSACTION_YEAR;


-- Revenue by quarter
SELECT
    YEAR(TRANSACTION_DATE) AS TRANSACTION_YEAR,
    QUARTER(TRANSACTION_DATE) AS QUARTER_NUMBER,
    SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM SALES_TRANSACTIONS
GROUP BY
    YEAR(TRANSACTION_DATE),
    QUARTER(TRANSACTION_DATE)
ORDER BY
    TRANSACTION_YEAR,
    QUARTER_NUMBER;
