-- COMMON TABLE EXPRESSIONS (CTE)


-- Calculate sales using CTE
WITH SALES_DATA AS (
    SELECT
        PRODUCT_NAME,
        CITY,
        QUANTITY,
        UNIT_PRICE,
        QUANTITY * UNIT_PRICE AS TOTAL_SALES
    FROM SALES_TRANSACTIONS
)
SELECT *
FROM SALES_DATA;


-- Find products with sales greater than 5000
WITH SALES_DATA AS (
    SELECT
        PRODUCT_NAME,
        QUANTITY * UNIT_PRICE AS TOTAL_SALES
    FROM SALES_TRANSACTIONS
)
SELECT
    PRODUCT_NAME,
    TOTAL_SALES
FROM SALES_DATA
WHERE TOTAL_SALES > 5000;


-- Calculate city-wise sales
WITH CITY_SALES AS (
    SELECT
        CITY,
        SUM(QUANTITY * UNIT_PRICE) AS TOTAL_SALES
    FROM SALES_TRANSACTIONS
    GROUP BY CITY
)
SELECT *
FROM CITY_SALES
ORDER BY TOTAL_SALES DESC;


-- Find highest-selling city
WITH CITY_SALES AS (
    SELECT
        CITY,
        SUM(QUANTITY * UNIT_PRICE) AS TOTAL_SALES
    FROM SALES_TRANSACTIONS
    GROUP BY CITY
)
SELECT *
FROM CITY_SALES
ORDER BY TOTAL_SALES DESC
LIMIT 1;


-- Find products above average sales
WITH PRODUCT_SALES AS (
    SELECT
        PRODUCT_NAME,
        SUM(QUANTITY * UNIT_PRICE) AS TOTAL_SALES
    FROM SALES_TRANSACTIONS
    GROUP BY PRODUCT_NAME
)
SELECT
    PRODUCT_NAME,
    TOTAL_SALES
FROM PRODUCT_SALES
WHERE TOTAL_SALES > (
    SELECT AVG(TOTAL_SALES)
    FROM PRODUCT_SALES
);
