-- DATA CLEANING


-- Find duplicate transaction IDs
SELECT
    TRANSACTION_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SALES_TRANSACTIONS
GROUP BY TRANSACTION_ID
HAVING COUNT(*) > 1;


-- Find missing product names
SELECT *
FROM SALES_TRANSACTIONS
WHERE PRODUCT_NAME IS NULL;


-- Find missing cities
SELECT *
FROM SALES_TRANSACTIONS
WHERE CITY IS NULL;


-- Find missing payment modes
SELECT *
FROM SALES_TRANSACTIONS
WHERE PAYMENT_MODE IS NULL;


-- Replace missing payment mode
SELECT
    PRODUCT_NAME,
    CITY,
    COALESCE(PAYMENT_MODE, 'Unknown') AS PAYMENT_MODE
FROM SALES_TRANSACTIONS;


-- Remove extra spaces
SELECT
    TRIM(PRODUCT_NAME) AS CLEAN_PRODUCT_NAME,
    TRIM(CITY) AS CLEAN_CITY
FROM SALES_TRANSACTIONS;


-- Convert product names to uppercase
SELECT
    UPPER(TRIM(PRODUCT_NAME)) AS CLEAN_PRODUCT_NAME
FROM SALES_TRANSACTIONS;


-- Convert city names to proper lowercase format
SELECT
    LOWER(TRIM(CITY)) AS CLEAN_CITY
FROM SALES_TRANSACTIONS;
