-- SUBQUERIES ANALYSIS

-- Find products with a unit price higher than the average unit price
SELECT PRODUCT_NAME, UNIT_PRICE
FROM SALES_TRANSACTIONS
WHERE UNIT_PRICE > (
    SELECT AVG(UNIT_PRICE)
    FROM SALES_TRANSACTIONS
);


-- Find transactions with the highest unit price
SELECT PRODUCT_NAME, UNIT_PRICE
FROM SALES_TRANSACTIONS
WHERE UNIT_PRICE = (
    SELECT MAX(UNIT_PRICE)
    FROM SALES_TRANSACTIONS
);


-- Find transactions with the lowest unit price
SELECT PRODUCT_NAME, UNIT_PRICE
FROM SALES_TRANSACTIONS
WHERE UNIT_PRICE = (
    SELECT MIN(UNIT_PRICE)
    FROM SALES_TRANSACTIONS
);


-- Find products whose quantity is greater than average quantity
SELECT PRODUCT_NAME, QUANTITY
FROM SALES_TRANSACTIONS
WHERE QUANTITY > (
    SELECT AVG(QUANTITY)
    FROM SALES_TRANSACTIONS
);


-- Find cities having sales greater than average city sales
SELECT CITY,
       SUM(QUANTITY * UNIT_PRICE) AS TOTAL_SALES
FROM SALES_TRANSACTIONS
GROUP BY CITY
HAVING SUM(QUANTITY * UNIT_PRICE) > (
    SELECT AVG(TOTAL_SALES)
    FROM (
        SELECT CITY,
               SUM(QUANTITY * UNIT_PRICE) AS TOTAL_SALES
        FROM SALES_TRANSACTIONS
        GROUP BY CITY
    ) AS CITY_SALES
)
ORDER BY TOTAL_SALES DESC;


-- Find the transaction with the highest total amount
SELECT PRODUCT_NAME,
       QUANTITY,
       UNIT_PRICE,
       QUANTITY * UNIT_PRICE AS TOTAL_AMOUNT
FROM SALES_TRANSACTIONS
WHERE QUANTITY * UNIT_PRICE = (
    SELECT MAX(QUANTITY * UNIT_PRICE)
    FROM SALES_TRANSACTIONS
);
