-- WINDOW FUNCTIONS


-- Rank products based on unit price
SELECT
    PRODUCT_NAME,
    UNIT_PRICE,
    RANK() OVER (ORDER BY UNIT_PRICE DESC) AS PRICE_RANK
FROM SALES_TRANSACTIONS;


-- Dense rank products based on unit price
SELECT
    PRODUCT_NAME,
    UNIT_PRICE,
    DENSE_RANK() OVER (ORDER BY UNIT_PRICE DESC) AS PRICE_RANK
FROM SALES_TRANSACTIONS;


-- Assign row number to transactions
SELECT
    PRODUCT_NAME,
    UNIT_PRICE,
    ROW_NUMBER() OVER (ORDER BY UNIT_PRICE DESC) AS ROW_NUM
FROM SALES_TRANSACTIONS;


-- Rank products within each city
SELECT
    CITY,
    PRODUCT_NAME,
    UNIT_PRICE,
    RANK() OVER (
        PARTITION BY CITY
        ORDER BY UNIT_PRICE DESC
    ) AS CITY_PRICE_RANK
FROM SALES_TRANSACTIONS;


-- Calculate running total of sales
SELECT
    TRANSACTION_DATE,
    PRODUCT_NAME,
    QUANTITY * UNIT_PRICE AS TOTAL_SALES,
    SUM(QUANTITY * UNIT_PRICE) OVER (
        ORDER BY TRANSACTION_DATE
    ) AS RUNNING_TOTAL
FROM SALES_TRANSACTIONS;


-- Calculate average sales
SELECT
    PRODUCT_NAME,
    QUANTITY * UNIT_PRICE AS TOTAL_SALES,
    ROUND(
        AVG(QUANTITY * UNIT_PRICE) OVER (), 2
    ) AS AVERAGE_SALES
FROM SALES_TRANSACTIONS;


-- Compare transaction sales with average sales
SELECT
    PRODUCT_NAME,
    QUANTITY * UNIT_PRICE AS TOTAL_SALES,
    ROUND(
        AVG(QUANTITY * UNIT_PRICE) OVER (), 2
    ) AS AVERAGE_SALES,
    CASE
        WHEN QUANTITY * UNIT_PRICE >
             AVG(QUANTITY * UNIT_PRICE) OVER ()
        THEN 'Above Average'
        ELSE 'Below Average'
    END AS SALES_STATUS
FROM SALES_TRANSACTIONS;
